import type { SolutionRecord } from "./types";

/**
 * Typed seed/mock data for the shell phase. Preserved from the Vite prototype
 * (`INITIAL_SOLUTIONS`). Replace with real Prisma-backed queries in a later phase.
 */
export const solutionsMock: SolutionRecord[] = [
  {
    id: "sol-1",
    name: "شُمّان",
    maturityStage: "نموذج أولي (Prototype)",
    governanceColumn: "احتضان فوري (Pilot)",
    owner: "إدارة الأصول والعمليات البيانية",
    source: "هاكاثون المعسكر",
    readinessPct: 62,
    problem: "غياب رؤية موحّدة لحالة الأصول يؤخر قرارات الصيانة",
    durationLabel: "6 أشهر",
    costLabel: "18٬000 ر.س",
    audience: "فرق تشغيل المحطات",
    strategicGoal: "رفع كفاءة التشغيل",
  },
  {
    id: "sol-2",
    name: "مدار (Madar AI)",
    maturityStage: "إثبات مفهوم (PoC)",
    governanceColumn: "قيد المراجعة الفنية",
    owner: "إدارة الأصول والعمليات البيانية",
    source: "هاكاثون المعسكر",
    readinessPct: 71,
    problem: "الاعتماد على التقارير التقليدية يؤدي لتأخر قرارات الصيانة قبل وقوع الأعطال",
    durationLabel: "6 أشهر",
    costLabel: "24٬000 ر.س",
    audience: "مهندسو محطات الطاقة الشمسية",
    strategicGoal: "تعزيز مظاهر الاستدامة",
  },
  {
    id: "sol-3",
    name: "سنَد (SANAD)",
    maturityStage: "نسخة تجريبية",
    governanceColumn: "احتضان فوري (Pilot)",
    owner: "الإدارة العامة لشبكات نقل الطاقة",
    source: "هاكاثون المعسكر",
    readinessPct: 90,
    problem: "بطء الاستجابة لأعطال الشبكة يزيد مدة الانقطاع",
    durationLabel: "9 أشهر",
    costLabel: "31٬000 ر.س",
    audience: "فرق الصيانة الميدانية",
    strategicGoal: "تحسين موثوقية الشبكة",
  },
  {
    id: "sol-4",
    name: "يّـن",
    maturityStage: "نموذج أولي (Prototype)",
    governanceColumn: "قيد المراجعة الفنية",
    owner: "إدارة التحول الرقمي",
    source: "هاكاثون المعسكر",
    readinessPct: 55,
    problem: "تشتت بيانات المستخدمين بين أنظمة متعددة",
    durationLabel: "4 أشهر",
    costLabel: "12٬000 ر.س",
    audience: "الموظفون الإداريون",
    strategicGoal: "تحسين تجربة الموظف",
  },
  {
    id: "sol-5",
    name: "مكتبة",
    maturityStage: "تشغيل فعلي",
    governanceColumn: "مكتملة",
    owner: "إدارة الأصول والعمليات البيانية",
    source: "مقترح داخلي",
    readinessPct: 100,
    problem: "صعوبة الوصول لأرشيف المستندات الفنية",
    durationLabel: "12 شهرًا",
    costLabel: "9٬000 ر.س",
    audience: "الموظفون التقنيون",
    strategicGoal: "تعزيز إدارة المعرفة",
  },
  {
    id: "sol-6",
    name: "نظام تنبيهات الصيانة الاستباقية للمحطات",
    maturityStage: "تشغيل فعلي",
    governanceColumn: "قيد المراجعة الفنية",
    owner: "إدارة الأصول والعمليات البيانية",
    source: "مقترح داخلي",
    readinessPct: 100,
    problem: "اكتشاف الأعطال بعد وقوعها بدل توقعها مسبقًا",
    durationLabel: "10 أشهر",
    costLabel: "27٬000 ر.س",
    audience: "مهندسو الصيانة",
    strategicGoal: "خفض التوقف غير المخطط",
  },
];
